all:
  children:
    daig_app:
      hosts:
        app-01:
          ansible_host: 127.0.0.1
          ansible_port: 2222
      vars:
        ansible_user: ubuntu
    daig_data:
      hosts:
        db-01:
          ansible_host: 127.0.0.1
          ansible_port: 2223
      vars:
        ansible_user: ubuntu
